### ISSUE TITLE
panic: runtime error: slice bounds out of range [1:0]

### ISSUE THREAD

**Issue by UnknownOre** [Sandertv/gophertunnel#138]
panic: runtime error: slice bounds out of range [1:0]

goroutine 25 [running]:
github.com/sandertv/gophertunnel/minecraft.(*Conn).ReadPacket(0xc000c61400)
        C:/Users/Ali/go/pkg/mod/github.com/sandertv/gophertunnel@v1.21.0/minecraft/conn.go:340 +0x47c
github.com/paroxity/portal/session.handlePackets.func2()
        C:/Users/Ali/go/pkg/mod/github.com/paroxity/portal@v0.0.0-20220522105321-137f7d4e9e72/session/packet_handler.go:107 +0x52
created by github.com/paroxity/portal/session.handlePackets
        C:/Users/Ali/go/pkg/mod/github.com/paroxity/portal@v0.0.0-20220522105321-137f7d4e9e72/session/packet_handler.go:104 +0x97

**Comment by UnknownOre** [comment]
this was caused by portal somehow, the latest portal version fixes it
